[[redirects]]
  from = "https://altair.fyi/*"
  to = "https://amitt.ai/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://altair.fyi"
  to = "https://amitt.ai"
  status = 301
  force = true
